// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Player.DataAccess;

#nullable disable

namespace Player.DataAccess.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20240404143313_MakeRoleIdNullable")]
    partial class MakeRoleIdNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Player.Domain.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("Player.Domain.AdHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("ObjectId");

                    b.ToTable("AdHistories");
                });

            modelBuilder.Entity("Player.Domain.AdLifetime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdvertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InArchive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("AdLifetimes");
                });

            modelBuilder.Entity("Player.Domain.AdTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("ObjectId");

                    b.ToTable("AdTimes");
                });

            modelBuilder.Entity("Player.Domain.Advert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdvertTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TrackTypeId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("Player.Domain.AdvertPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlayingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("AdvertPlaylists");
                });

            modelBuilder.Entity("Player.Domain.AdvertType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdvertTypes");
                });

            modelBuilder.Entity("Player.Domain.BannedMusicInObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicTrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MusicTrackId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("BannedMusicInObject");
                });

            modelBuilder.Entity("Player.Domain.CheapPlaylistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObjectInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObjectInfoId");

                    b.ToTable("CheapPlaylistTemplates");
                });

            modelBuilder.Entity("Player.Domain.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Player.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Player.Domain.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Player.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Player.Domain.Interval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("BeginTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<Guid?>("ObjectInfoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrackTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObjectInfoId");

                    b.HasIndex("TrackTypeId");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("Player.Domain.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Player.Domain.MusicHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MusicTrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MusicTrackId");

                    b.HasIndex("ObjectId");

                    b.ToTable("MusicHistories");
                });

            modelBuilder.Entity("Player.Domain.MusicTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackTypeId");

                    b.HasIndex("UploaderId");

                    b.ToTable("MusicTracks");
                });

            modelBuilder.Entity("Player.Domain.MusicTrackGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicTrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MusicTrackId");

                    b.ToTable("MusicTrackGenres");
                });

            modelBuilder.Entity("Player.Domain.MusicTrackPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicTrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlayingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MusicTrackId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("MusicTrackPlaylists");
                });

            modelBuilder.Entity("Player.Domain.MusicTrackSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("MusicTrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MusicTrackId");

                    b.HasIndex("SelectionId");

                    b.ToTable("MusicTrackSelections");
                });

            modelBuilder.Entity("Player.Domain.ObjectInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActualAddress")
                        .HasColumnType("text");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("Attendance")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("BeginTime")
                        .HasColumnType("interval");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientSettings")
                        .HasColumnType("jsonb");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string[]>("FreeDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("array[]::varchar[]");

                    b.Property<string>("Geolocation")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastOnlineTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalAddress")
                        .HasColumnType("text");

                    b.Property<int>("MaxAdvertBlockInSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RentersCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceCompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("SilentBlockInterval")
                        .HasColumnType("integer");

                    b.Property<double>("SilentPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CityId");

                    b.HasIndex("ServiceCompanyId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Player.Domain.ObjectSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("SelectionId");

                    b.ToTable("ObjectSelections");
                });

            modelBuilder.Entity("Player.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Player.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Player.Domain.PlayerTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Player.Domain.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdvertsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<double>("Loading")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Overloaded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PlayingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RebuildIsNeeded")
                        .HasColumnType("boolean");

                    b.Property<int>("UniqueAdvertsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Player.Domain.PlaylistInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistInfos", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdminRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Player.Domain.RolePermissions", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Player.Domain.Selection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("Player.Domain.ServiceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceCompanies");
                });

            modelBuilder.Entity("Player.Domain.TrackType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrackTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("225ea1d7-ede3-4733-ba4a-8ed9459f94c6"),
                            Code = "Advert",
                            Name = "Реклама"
                        },
                        new
                        {
                            Id = new Guid("b8b2d657-394e-45a3-9a4d-25ffba47dcaf"),
                            Code = "Music",
                            Name = "Музыка"
                        },
                        new
                        {
                            Id = new Guid("cdd0f07d-e4af-43d3-9a28-3b8674649fe4"),
                            Code = "Silent",
                            Name = "Тишина"
                        });
                });

            modelBuilder.Entity("Player.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07abf324-2fc7-44fd-ba41-ada305a33c9d"),
                            Email = "system@walkman.org"
                        });
                });

            modelBuilder.Entity("Player.Domain.UserObjects", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ObjectId");

                    b.HasIndex("ObjectId");

                    b.ToTable("UserObjects");
                });

            modelBuilder.Entity("Player.Domain.AdHistory", b =>
                {
                    b.HasOne("Player.Domain.Advert", "Advert")
                        .WithMany("AdHistories")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Player.Domain.AdLifetime", b =>
                {
                    b.HasOne("Player.Domain.Advert", "Advert")
                        .WithMany("AdLifetimes")
                        .HasForeignKey("AdvertId");

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Player.Domain.AdTime", b =>
                {
                    b.HasOne("Player.Domain.Advert", "Advert")
                        .WithMany("AdTimes")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Player.Domain.Advert", b =>
                {
                    b.HasOne("Player.Domain.AdvertType", "AdvertType")
                        .WithMany()
                        .HasForeignKey("AdvertTypeId");

                    b.HasOne("Player.Domain.Organization", "Organization")
                        .WithMany("Adverts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.TrackType", "TrackType")
                        .WithMany()
                        .HasForeignKey("TrackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertType");

                    b.Navigation("Organization");

                    b.Navigation("TrackType");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Player.Domain.AdvertPlaylist", b =>
                {
                    b.HasOne("Player.Domain.Advert", "Advert")
                        .WithMany("Playlists")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.Playlist", "Playlist")
                        .WithMany("Aderts")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Player.Domain.BannedMusicInObject", b =>
                {
                    b.HasOne("Player.Domain.MusicTrack", "MusicTrack")
                        .WithMany()
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany("BannedMusicInObjects")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicTrack");

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Player.Domain.CheapPlaylistTemplate", b =>
                {
                    b.HasOne("Player.Domain.ObjectInfo", "ObjectInfo")
                        .WithMany()
                        .HasForeignKey("ObjectInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectInfo");
                });

            modelBuilder.Entity("Player.Domain.Client", b =>
                {
                    b.HasOne("Player.Domain.Organization", "Organization")
                        .WithMany("Clients")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Player.Domain.Image", b =>
                {
                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany("Images")
                        .HasForeignKey("ObjectId");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Player.Domain.Interval", b =>
                {
                    b.HasOne("Player.Domain.ObjectInfo", null)
                        .WithMany("Intervals")
                        .HasForeignKey("ObjectInfoId");

                    b.HasOne("Player.Domain.TrackType", "TrackType")
                        .WithMany()
                        .HasForeignKey("TrackTypeId");

                    b.Navigation("TrackType");
                });

            modelBuilder.Entity("Player.Domain.Manager", b =>
                {
                    b.HasOne("Player.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Player.Domain.MusicHistory", b =>
                {
                    b.HasOne("Player.Domain.MusicTrack", "MusicTrack")
                        .WithMany("MusicHistories")
                        .HasForeignKey("MusicTrackId");

                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId");

                    b.Navigation("MusicTrack");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Player.Domain.MusicTrack", b =>
                {
                    b.HasOne("Player.Domain.TrackType", "TrackType")
                        .WithMany()
                        .HasForeignKey("TrackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackType");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Player.Domain.MusicTrackGenre", b =>
                {
                    b.HasOne("Player.Domain.Genre", "Genre")
                        .WithMany("MusicTracks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.MusicTrack", "MusicTrack")
                        .WithMany("Genres")
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MusicTrack");
                });

            modelBuilder.Entity("Player.Domain.MusicTrackPlaylist", b =>
                {
                    b.HasOne("Player.Domain.MusicTrack", "MusicTrack")
                        .WithMany("Playlists")
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.Playlist", "Playlist")
                        .WithMany("MusicTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicTrack");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Player.Domain.MusicTrackSelection", b =>
                {
                    b.HasOne("Player.Domain.MusicTrack", "MusicTrack")
                        .WithMany("Selections")
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.Selection", "Selection")
                        .WithMany("MusicTracks")
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicTrack");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Player.Domain.ObjectInfo", b =>
                {
                    b.HasOne("Player.Domain.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.ServiceCompany", "ServiceCompany")
                        .WithMany()
                        .HasForeignKey("ServiceCompanyId");

                    b.OwnsOne("Player.Domain.ObjectInfo+ResponsiblePerson", "ResponsiblePersonOne", b1 =>
                        {
                            b1.Property<Guid>("ObjectInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ComplexName")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("ObjectInfoId");

                            b1.ToTable("Objects");

                            b1.WithOwner()
                                .HasForeignKey("ObjectInfoId");
                        });

                    b.OwnsOne("Player.Domain.ObjectInfo+ResponsiblePerson", "ResponsiblePersonTwo", b1 =>
                        {
                            b1.Property<Guid>("ObjectInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ComplexName")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("ObjectInfoId");

                            b1.ToTable("Objects");

                            b1.WithOwner()
                                .HasForeignKey("ObjectInfoId");
                        });

                    b.Navigation("ActivityType");

                    b.Navigation("City");

                    b.Navigation("ResponsiblePersonOne");

                    b.Navigation("ResponsiblePersonTwo");

                    b.Navigation("ServiceCompany");
                });

            modelBuilder.Entity("Player.Domain.ObjectSelection", b =>
                {
                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany("Selections")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.Selection", "Selection")
                        .WithMany("Objects")
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Player.Domain.Playlist", b =>
                {
                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany("Playlists")
                        .HasForeignKey("ObjectId");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Player.Domain.PlaylistInfo", b =>
                {
                    b.HasOne("Player.Domain.Playlist", "Playlist")
                        .WithMany("PlaylistInfos")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Player.Domain.RolePermissions", b =>
                {
                    b.HasOne("Player.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Player.Domain.Selection", b =>
                {
                    b.HasOne("Player.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Player.Domain.User", b =>
                {
                    b.HasOne("Player.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Player.Domain.UserObjects", b =>
                {
                    b.HasOne("Player.Domain.ObjectInfo", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.User", "User")
                        .WithMany("Objects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Player.Domain.Advert", b =>
                {
                    b.Navigation("AdHistories");

                    b.Navigation("AdLifetimes");

                    b.Navigation("AdTimes");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Player.Domain.Genre", b =>
                {
                    b.Navigation("MusicTracks");
                });

            modelBuilder.Entity("Player.Domain.MusicTrack", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("MusicHistories");

                    b.Navigation("Playlists");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Player.Domain.ObjectInfo", b =>
                {
                    b.Navigation("BannedMusicInObjects");

                    b.Navigation("Images");

                    b.Navigation("Intervals");

                    b.Navigation("Playlists");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Player.Domain.Organization", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Player.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Player.Domain.Playlist", b =>
                {
                    b.Navigation("Aderts");

                    b.Navigation("MusicTracks");

                    b.Navigation("PlaylistInfos");
                });

            modelBuilder.Entity("Player.Domain.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Player.Domain.Selection", b =>
                {
                    b.Navigation("MusicTracks");

                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Player.Domain.User", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
