FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Player.PlaylistGenerator/Player.PlaylistGenerator.csproj", "Player.PlaylistGenerator/"]
COPY ["Player.DataAccess/Player.DataAccess.csproj", "Player.DataAccess/"]
COPY ["Player.Helpers/Player.Helpers.csproj", "Player.Helpers/"]
COPY ["Player.Domain/Player.Domain.csproj", "Player.Domain/"]
COPY ["Player.DTOs/Player.DTOs.csproj", "Player.DTOs/"]
COPY ["Player.BusinessLogic/Player.BusinessLogic.csproj", "Player.BusinessLogic/"]
COPY ["Player.Services/Player.Services.csproj", "Player.Services/"]
COPY ["Player.Services.Abstractions/Player.Services.Abstractions.csproj", "Player.Services.Abstractions/"]
COPY ["Player.Helpers.App/Player.Helpers.App.csproj", "Player.Helpers.App/"]
RUN dotnet restore "Player.PlaylistGenerator/Player.PlaylistGenerator.csproj"
COPY . .
WORKDIR "/src/Player.PlaylistGenerator"
RUN dotnet build "Player.PlaylistGenerator.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Player.PlaylistGenerator.csproj" -c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Player.PlaylistGenerator.dll"]
