FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
RUN apt-get update
RUN apt-get -y install libxrender1 libfontconfig1 libxtst6

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Player.ReportSender/Player.ReportSender.csproj", "Player.ReportSender/"]
COPY ["Player.DataAccess/Player.DataAccess.csproj", "Player.DataAccess/"]
COPY ["Player.Services/Player.Services.csproj", "Player.Services/"]
COPY ["Player.Domain/Player.Domain.csproj", "Player.Domain/"]
COPY ["Player.Helpers/Player.Helpers.csproj", "Player.Helpers/"]
COPY ["Player.Services.Abstractions/Player.Services.Abstractions.csproj", "Player.Services.Abstractions/"]
COPY ["Player.DTOs/Player.DTOs.csproj", "Player.DTOs/"]
COPY ["Player.Helpers.App/Player.Helpers.App.csproj", "Player.Helpers.App/"]
RUN dotnet restore "Player.ReportSender/Player.ReportSender.csproj"
COPY . .
RUN chmod +x "Player.Services/wkhtmltopdf/Linux/wkhtmltopdf"
WORKDIR "/src/Player.ReportSender"
RUN dotnet build "Player.ReportSender.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Player.ReportSender.csproj" -c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Player.ReportSender.dll"]
