FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Player.ArchiveWorker/Player.ArchiveWorker.csproj", "Player.ArchiveWorker/"]
COPY ["Player.DataAccess/Player.DataAccess.csproj", "Player.DataAccess/"]
COPY ["Player.Domain/Player.Domain.csproj", "Player.Domain/"]
COPY ["Player.Helpers.App/Player.Helpers.App.csproj", "Player.Helpers.App/"]
COPY ["Player.Helpers/Player.Helpers.csproj", "Player.Helpers/"]
COPY ["Player.DTOs/Player.DTOs.csproj", "Player.DTOs/"]
RUN dotnet restore "Player.ArchiveWorker/Player.ArchiveWorker.csproj"
COPY . .
WORKDIR "/src/Player.ArchiveWorker"
RUN dotnet build "Player.ArchiveWorker.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Player.ArchiveWorker.csproj" -c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Player.ArchiveWorker.dll"]
